import { useEffect, useRef } from 'react';
import Header from './Header';
import Sidebar from './Sidebar';
import EditorArea from './EditorArea';
import RightPanel from './RightPanel';
import BottomPanel from './BottomPanel';
import Overlays from './Overlays';
import { useApp } from '../lib/store';
import { bridge, desktop } from '../lib/bridge';
import { GitBranch, LockKeyhole, CircleDot, Terminal, ChevronRight, Check } from './Icons';
function Divider({axis,panel}:{axis:'x'|'y';panel:'sidebar'|'right'|'bottom'}){const s=useApp();const start=(event:React.PointerEvent<HTMLDivElement>)=>{event.currentTarget.setPointerCapture(event.pointerId);const origin=axis==='x'?event.clientX:event.clientY;const initial=panel==='sidebar'?s.sidebarWidth:panel==='right'?s.rightWidth:s.bottomHeight;const move=(e:PointerEvent)=>{const delta=(axis==='x'?e.clientX:e.clientY)-origin;const value=panel==='sidebar'?Math.max(194,Math.min(430,initial+delta)):panel==='right'?Math.max(260,Math.min(610,initial-delta)):Math.max(124,Math.min(window.innerHeight-270,initial-delta));s.set(panel==='sidebar'?{sidebarWidth:value}:panel==='right'?{rightWidth:value}:{bottomHeight:value})};const end=()=>{window.removeEventListener('pointermove',move);window.removeEventListener('pointerup',end)};window.addEventListener('pointermove',move);window.addEventListener('pointerup',end)};return <div className={`resize-handle resize-${axis}`} onPointerDown={start}/>}
export default function App(){const s=useApp();const handler=useRef(s.handleProcess);handler.current=s.handleProcess;const debugHandler=useRef(s.handleDebug);debugHandler.current=s.handleDebug;useEffect(()=>{void useApp.getState().initialize();const off=bridge?.onProcess(event=>handler.current(event));const offDebug=bridge?.onDebug(event=>debugHandler.current(event));return()=>{off?.();offDebug?.()}},[]);useEffect(()=>{const key=(e:KeyboardEvent)=>{const mod=e.ctrlKey||e.metaKey;if(mod&&e.shiftKey&&e.key.toLowerCase()==='p'){e.preventDefault();useApp.getState().set({palette:true})}if(mod&&e.key.toLowerCase()==='s'){e.preventDefault();void useApp.getState().saveDoc()}if(mod&&e.key==='`'){e.preventDefault();const state=useApp.getState();state.set({bottomOpen:true,bottomTab:'terminal'});if(!state.jobs.length&&state.workspace?.trusted)void state.startTerminal()}if(e.key==='Escape'&&useApp.getState().palette)useApp.getState().set({palette:false})};const before=(e:BeforeUnloadEvent)=>{if(useApp.getState().docs.some(d=>d.content!==d.saved)){e.preventDefault()}};window.addEventListener('keydown',key);window.addEventListener('beforeunload',before);return()=>{window.removeEventListener('keydown',key);window.removeEventListener('beforeunload',before)}},[]);const current=s.docs.find(d=>d.path===s.activePath);return <div className="app-shell"><Header/><div className="body-shell"><Sidebar/>{s.sidebarOpen&&<Divider axis="x" panel="sidebar"/>}<div className="work-area"><div className="upper-area"><EditorArea/>{s.rightOpen&&<><Divider axis="x" panel="right"/><RightPanel/></>}</div>{s.bottomOpen&&<><Divider axis="y" panel="bottom"/><BottomPanel/></>}</div></div><footer className="statusbar"><div className="status-left"><span className="status-brand">R.</span><button onClick={()=>s.set({activity:'git',sidebarOpen:true})}><GitBranch size={12}/>{s.info?.git?s.workspace?.name:'no repository'}</button><button onClick={()=>s.set({activity:'verification',sidebarOpen:true})}><CircleDot size={12}/> diagnostics not collected</button></div><div className="status-right"><span>{!desktop?'BROWSER PREVIEW':s.workspace?.trusted?'LOCAL WORKSPACE':s.workspace?'RESTRICTED MODE':'NO WORKSPACE'}</span>{current&&<><span className="status-sep"/><span>UTF-8</span><span>{current.path.split('.').at(-1)?.toUpperCase()}</span></>}<span className="status-sep"/><span className="status-build">RYVEN 0.1.1</span></div></footer><Overlays/></div>}
