import { useEffect, useRef } from 'react';
import { Terminal as XTerminal } from '@xterm/xterm';
import { FitAddon } from '@xterm/addon-fit';
import { useApp } from '../lib/store';
import { bridge } from '../lib/bridge';
import { Terminal, FlaskConical, CircleDot, Plus, X, Square, ChevronDown, PanelBottomClose, Check, Play } from './Icons';
function TerminalCanvas({id}:{id:string}){const ref=useRef<HTMLDivElement>(null);useEffect(()=>{const el=ref.current;if(!el)return;const term=new XTerminal({convertEol:true,fontFamily:'"SFMono-Regular", Consolas, "Liberation Mono", monospace',fontSize:12,lineHeight:1.3,theme:{background:'#111516',foreground:'#c8d1ca',cursor:'#a8c879',selectionBackground:'#344338'},cursorBlink:true,scrollback:4000});const fit=new FitAddon();term.loadAddon(fit);term.open(el);const job=useApp.getState().jobs.find(j=>j.id===id);term.write(job?.output||'');const disposable=term.onData(data=>bridge?.sendInput(id,data).catch(()=>{}));let last=job?.output.length||0;const unsubscribe=useApp.subscribe(state=>{const text=state.jobs.find(j=>j.id===id)?.output||'';if(text.length<last){term.reset();last=0;}if(text.length>last){term.write(text.slice(last));last=text.length;}});const resize=new ResizeObserver(()=>{try{fit.fit()}catch{}});resize.observe(el);setTimeout(()=>{try{fit.fit()}catch{}},50);return()=>{resize.disconnect();unsubscribe();disposable.dispose();term.dispose()};},[id]);return <div className="xterm-host" ref={ref}/>}
function TestResult(){const s=useApp();const tests=s.jobs.filter(j=>j.task==='test').slice().reverse();return <div className="results-pane"><div className="results-heading"><div><span className="section-kicker">REAL TEST RUNS</span><h3>Test results</h3></div><button className="small-accent" disabled={!s.info?.test||!s.workspace?.trusted} onClick={()=>s.runTask('test')}><Play size={12}/> Run tests</button></div>{tests.length===0?<div className="bottom-empty"><FlaskConical size={21}/><span>No tests run in this session.</span><small>{s.info?.test?'Run the configured test task to see its output.':'No test runner configuration detected.'}</small></div>:<div className="test-history">{tests.map(j=><button className={`test-run ${s.activeJob===j.id?'active':''}`} key={j.id} onClick={()=>s.set({activeJob:j.id})}><span className={`result-dot ${j.running?'pending':j.exitCode===0?'success':'failure'}`}/>{j.label}<span>{j.running?'RUNNING':j.exitCode===0?'PASSED':'FAILED'}</span></button>)}</div>}{s.activeJob&&tests.some(j=>j.id===s.activeJob)?<div className="result-output"><TerminalCanvas id={s.activeJob}/></div>:tests.length>0&&<div className="bottom-empty"><span>Select a test run to view its real output.</span></div>}</div>}
function Problems(){return <div className="bottom-empty"><CircleDot size={20}/><span>No diagnostics collected</span><small>Monaco reports editor diagnostics inline. Unified Problems and LSP diagnostics are coming soon.</small></div>}
export default function BottomPanel(){const s=useApp();const active=s.jobs.find(j=>j.id===s.activeJob);return <section className="bottom-panel" style={{height:s.bottomHeight}}><div className="bottom-toolbar"><div className="bottom-tabs"><button className={s.bottomTab==='terminal'?'active':''} onClick={()=>s.set({bottomTab:'terminal'})}><Terminal size={14}/> TERMINAL</button><button className={s.bottomTab==='tests'?'active':''} onClick={()=>s.set({bottomTab:'tests'})}><FlaskConical size={14}/> TESTS</button><button className={s.bottomTab==='problems'?'active':''} onClick={()=>s.set({bottomTab:'problems'})}><CircleDot size={14}/> PROBLEMS</button><button className={s.bottomTab==='output'?'active':''} onClick={()=>s.set({bottomTab:'output'})}>OUTPUT</button></div><div className="bottom-actions">{s.bottomTab==='terminal'&&<button title="New terminal" disabled={!s.workspace?.trusted} onClick={s.startTerminal}><Plus size={16}/></button>}{active?.running&&<button title="Stop process" onClick={()=>s.stopJob(active.id)}><Square size={13}/></button>}<button title="Close panel" onClick={()=>s.set({bottomOpen:false})}><X size={16}/></button></div></div>{s.bottomTab==='terminal'||s.bottomTab==='output'?<><div className="terminal-tabs">{s.jobs.length===0?<span>NO ACTIVE SESSIONS</span>:s.jobs.map((j,i)=><button className={s.activeJob===j.id?'active':''} key={j.id} onClick={()=>s.set({activeJob:j.id})}><span className={`result-dot ${j.running?'success':j.exitCode===0?'pending':'failure'}`}/><span>{j.task==='terminal'?`Terminal ${s.jobs.slice(0,i+1).filter(x=>x.task==='terminal').length}`:j.label}</span></button>)}<div className="tabs-spacer"/><span className="terminal-cwd" title={s.workspace?.path}>{s.workspace?.name||'NO WORKSPACE'}</span></div>{s.activeJob?<TerminalCanvas key={s.activeJob} id={s.activeJob}/>:<div className="bottom-empty terminal-empty"><Terminal size={21}/><span>Ready when you are.</span><small>{s.workspace?.trusted?'Start a terminal or run a configured task.':'Open and trust a workspace to start a terminal.'}</small>{s.workspace?.trusted&&<button className="small-accent" onClick={s.startTerminal}><Plus size={13}/> New terminal</button>}</div>}</>:s.bottomTab==='tests'?<TestResult/>:<Problems/>}</section>}
