export type Entry = { name: string; path: string; kind: 'file' | 'folder'; children?: Entry[] };
export type Workspace = { path: string; name: string; trusted: boolean };
export type Recent = { path: string; name: string; trusted: boolean; opened: number };
export type Tool = { name: string; available: boolean; version?: string };
export type ProjectInfo = { scripts: Record<string, string>; kind: string; git: boolean; run?: string; test?: string; build?: string };
export type ProcessEvent = { id: string; data?: string; exitCode?: number | null; kind: 'data' | 'exit' };
export type Job = { id: string; label: string; command: string };
export type Template = 'web-react' | 'web-vanilla' | 'node-api' | 'python-cli' | 'blank';
export type CreateOptions = { parent: string; name: string; template: Template; initializeGit: boolean };
export type CreateResult = { workspace: Workspace; files: string[]; steps: string[] };
export type SecurityFinding = { id: string; category: 'secret' | 'dependency'; source: string; severity: 'critical' | 'high' | 'moderate' | 'medium' | 'low' | 'unknown'; title: string; location: string; evidence: string };
export type SecurityReport = { scannedAt: number; scanners: string[]; findings: SecurityFinding[]; errors: string[]; scope: string };
export type AIRequest = { provider: 'openai-compatible' | 'anthropic-compatible'; endpoint: string; model: string; apiKey: string; question: string; fileName?: string; code?: string; authorized: boolean };
export type DebugFrame = { id: string; functionName: string; file: string; line: number; column: number };
export type DebugVariable = { name: string; type: string; value: string };
export type DebugSession = { id: string; entry: string; status: 'starting' | 'running' | 'paused' | 'stopped' | 'error'; reason?: string; frames: DebugFrame[]; variables: DebugVariable[]; output?: string; error?: string };
export type DebugAction = 'resume' | 'pause' | 'stepOver' | 'stepInto' | 'stepOut';
export type ExtensionManifest = { id:string; name:string; version:string; description:string; permissions:['snippets']; snippets:{label:string;language:string;body:string}[] };
export interface RyvenBridge {
  platform: string;
  selectWorkspace(): Promise<Workspace | null>;
  openWorkspace(path: string): Promise<Workspace>;
  setTrust(trusted: boolean): Promise<Workspace>;
  recent(): Promise<Recent[]>;
  selectProjectParent(): Promise<string | null>;
  createProject(options: CreateOptions): Promise<CreateResult>;
  list(path?: string): Promise<Entry[]>;
  read(path: string): Promise<string>;
  write(path: string, content: string): Promise<void>;
  createEntry(path: string, kind: 'file' | 'folder'): Promise<void>;
  projectInfo(): Promise<ProjectInfo>;
  detectTools(): Promise<Tool[]>;
  gitStatus(): Promise<string>;
  scanSecurity(): Promise<SecurityReport>;
  askAI(request: AIRequest): Promise<string>;
  startTerminal(): Promise<Job>;
  runTask(task: 'run' | 'test' | 'build' | 'git-status'): Promise<Job>;
  sendInput(id: string, data: string): Promise<void>;
  stopJob(id: string): Promise<void>;
  startDebug(entry?: string): Promise<DebugSession>;
  debugAction(action: DebugAction): Promise<void>;
  debugBreakpoint(file: string, line: number, condition?:string): Promise<{id:string;file:string;line:number;condition?:string}>;
  removeDebugBreakpoint(id: string): Promise<void>;
  debugEvaluate(expression: string): Promise<string>;
  stopDebug(): Promise<void>;
  onDebug(callback: (event: DebugSession) => void): () => void;
  listExtensions(): Promise<ExtensionManifest[]>;
  selectExtension(): Promise<ExtensionManifest | null>;
  installExtension(): Promise<ExtensionManifest[]>;
  removeExtension(id:string): Promise<ExtensionManifest[]>;
  openExternalPreview(url: string): Promise<void>;
  onProcess(callback: (event: ProcessEvent) => void): () => void;
  onProject(callback: (step: string) => void): () => void;
}
